application: scribeley
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /css
  static_dir: css
- url: /.*
  script: blog.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
